"""Initial commit

Revision ID: dae543ae6532
Revises: 
Create Date: 2023-02-20 17:28:13.362679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dae543ae6532'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('LSTAT',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fl_db', sa.String(length=255), nullable=False),
    sa.Column('fl_name', sa.String(length=255), nullable=False),
    sa.Column('fl_title', sa.String(length=255), nullable=False),
    sa.Column('fl_count', sa.BigInteger(), nullable=False),
    sa.Column('fl_guid', sa.String(length=255), nullable=False),
    sa.Column('fl_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='lstat'
    )
    op.create_index(op.f('ix_lstat_LSTAT_fl_db'), 'LSTAT', ['fl_db'], unique=False, schema='lstat')
    op.create_index(op.f('ix_lstat_LSTAT_fl_guid'), 'LSTAT', ['fl_guid'], unique=False, schema='lstat')
    op.create_index(op.f('ix_lstat_LSTAT_fl_name'), 'LSTAT', ['fl_name'], unique=False, schema='lstat')
    op.create_index(op.f('ix_lstat_LSTAT_fl_title'), 'LSTAT', ['fl_title'], unique=False, schema='lstat')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lstat_LSTAT_fl_title'), table_name='LSTAT', schema='lstat')
    op.drop_index(op.f('ix_lstat_LSTAT_fl_name'), table_name='LSTAT', schema='lstat')
    op.drop_index(op.f('ix_lstat_LSTAT_fl_guid'), table_name='LSTAT', schema='lstat')
    op.drop_index(op.f('ix_lstat_LSTAT_fl_db'), table_name='LSTAT', schema='lstat')
    op.drop_table('LSTAT', schema='lstat')
    # ### end Alembic commands ###
